# Generated by Django 5.1.4 on 2024-12-08 22:22

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='codigo_confirmacao',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Confirmação'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='noites',
            field=models.IntegerField(default=0, verbose_name='Noites'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='num_adultos',
            field=models.IntegerField(default=1, verbose_name='Número de Adultos'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CHECKIN', 'Check-in Realizado'), ('CHECKOUT', 'Check-out Realizado'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='CONFIRMADA', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='taxa_limpeza',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='BRL', max_digits=10, verbose_name='Taxa de Limpeza'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='taxa_servico',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='BRL', max_digits=10, verbose_name='Taxa de Serviço'),
        ),
    ]
